name: Continuous integration
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * THU'

jobs:
  tests:
    name: Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        drupal_version: [ '8.8', '8.9', '9.0', '9.1', '9.2' ]
        module: ['potion']
        experimental: [ false ]
        include:
          - drupal_version: '9.3'
            module: 'potion'
            experimental: true

    steps:
      - uses: actions/checkout@v1
      - run: docker-compose -f docker-compose.yml pull --include-deps drupal
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml build --pull --build-arg BASE_IMAGE_TAG=${{ matrix.drupal_version }} drupal
        continue-on-error: ${{ matrix.experimental }}
      - name: Run unit tests
        run: docker-compose -f docker-compose.yml run -u www-data drupal phpunit --no-coverage --group=${{ matrix.module }} --exclude-group=${{ matrix.module }}_functional --configuration=/var/www/html/phpunit.xml
        continue-on-error: ${{ matrix.experimental }}
